### PR TITLE
Match sourcemaps to specific JS files

### PR DESCRIPTION
**Pull request by dfreeman**
We've been running into an issue where Bugsnag wasn't able to do anything with our sourcemaps, and eventually tracked it to the fact that the wrong sourcemaps were being associated to our uploaded JS files.

It turns out `ember-asset-loader` (which is used by `ember-engines`) generates a `node-asset-manifest.js` file that doesn't have a corresponding sourcemap, and the upload process here assumes a 1:1 matching between JS files and maps.

This PR updates the logic to go through and line up the maps and JS files by name, which in a couple of trial deploys solved our mapping issues in Bugsnag.

### CODE REVIEW

**Comment by dfreeman** [comment]
Travis seems to be failing because recent Ember dropped support for PhantomJS and uses `WeakMap`. It seems like the tests are just the out-of-the-box blueprint tests, though?

**Review by jordpo — APPROVED** [review]

**Comment by jordpo** [comment]
yeah @dfreeman there aren't any tests so I'm not worried about the Travis build failing.

**Comment by dfreeman** [comment]
Thanks @jordpo! Could you cut a release when you have the chance? I'd like to avoid switching us over to an internal fork 🙂

**Comment by jordpo** [comment]
@patrickberkeley can you cut a release for this when you can?

**Comment by patrickberkeley** [comment]
@dfreeman @jordpo v0.1.3 has been pushed

**Pull request merged**
