### PR TITLE
Cleanup, updates, and a bugfix

### PR DESCRIPTION
**Pull request by cafreeman**
Hi there!
# What this is
My team currently uses this plugin for deploying our app. It's very useful! But, also it has a bug that has been wrecking our deploy pipeline for a while now (the same bug that was reported [here](https://github.com/IcarusWorks/ember-cli-deploy-bugsnag/issues/10)).

I decided to try and track down the source of the bug and fix it, but in the process I encountered a number of issues just getting this plugin running locally because of a number of dependency versions that constrain themselves to versions of Node that are pretty far outside the current LTS range.

So, I took it upon myself to go ahead and update this plugin to a current set of dependencies and syntax, fix the bug, and document a lot of the functions in the code that took me a while to parse the first time around.

# What's in this PR
More succinctly, this PR:
- Removes a ton of extraneous dependencies and files that weren't being used
- Updates all remaining dependencies to current(-ish) versions that will work with Node 6+
- Updates ember-cli to 3.4
- Adds linting and formatting
- Documents most of the plugin functionality via inline comments
- Fixes a bug where the minified URL would end up being `<publicDomain>undefined>` rather than `<publicDomain>/<path/to/file>`.
- Alleviates some of the reliance on regular expressions by instead relying on the `path` module to do a lot of the file name parsing.
- Fixes a potential issue with the `overwrite` flag where the `overwrite` property would *always* be sent to the bugsnag API, with either a value of true or false. The bugsnag API doesn't look at the value, but instead looks for the **presence** of the `overwrite` property, so even if you set `overwrite` to false, the bugsnag API would overwrite them anyway.

We were originally considering just starting from the ground up and releasing a new addon for fear that you might not be interested in such a big set of changes, but I figure it's much better to start by trying to contribute back :)

# More about the bugfix

So, as described above, the bug is that the minifiedUrl being sent to bugsnag would end up being, for example, `https://foo.comundefined` rather than `https://foo.com/assets/foo-123edfabe3bdb3bde324890.js`. This would typically cause Bugsnag to throw an error, claiming that it had received a duplicate file (because every upload would have `undefined` instead of the fingerprinted filename). This, in turn, would fail CI and also cause issues with linking the sourcemaps to specific releases when viewing errors in Bugsnag.

The culrpit ended up being the `getBaseFileName` function. It's goal was to take a fully qualified file path and return JUST the directory path and file name (e.g. `assets/foo` from `assets/foo-12345.js` so it could use the "base" name as a key to match JS files to source maps, ignoring the differences in their fingerprints.

The problem was that `getBaseFileName` used to do this with a regular expression:
```js
file.replace(/-[0-9a-f]+\.(js|map)$/, '')
```

Which would *only* match assets with fingerprints present. This is a problem because it's not always the case that every file with contain a fingerprint every time it is passed to `getBaseFileName`. In the event that the fingerprint had already been removed, the entire regex pattern wouldn't match, and `getBaseFileName` would return the exact same file path.

This meant that the plugin would end up indexing the files with keys like `assets/foo.js` instead of `assets/foo`, which mean that when the plugin tried to match the sourcemap to the js file by doing `jsFiles[getBaseFileName(mapFile)]`, it wouldn't find a match because `jsFiles` would be indexed with extensions, but the "base file name" of the map file would be `assets/foo`, hence the `undefined`.

To fix this, I changed `getBaseFileName` to break removing the fingerprint and removing the extension into two separate steps, and the tweaked the fingerprint regex so that it wouldn't have any problems if no fingerprint were present.

### CODE REVIEW

**Review by patrickberkeley — APPROVED** [review]
@cafreeman 🏆

**Review by jordpo — APPROVED** [review]
💯

**Comment by patrickberkeley** [comment]
@cafreeman 0.2.0 has been published.

**Comment by cafreeman** [comment]
@patrickberkeley awesome!! thanks y'all!

**Pull request merged**
